site_name: Xajax Docs
docs_dir: docs
theme: readthedocs
pages:
- Home: index.md
- About Xajax: about.md
- Xajax PHP Classes:
  - Response Class:
#    - Response_php/addCommand.md
    - Response_php/addHandler.md
    - Response_php/addPluginCommand.md
    - Response_php/alert.md
    - Response_php/append.md
    - Response_php/appendResponse.md
    - Response_php/assign.md
    - Response_php/call.md
    - Response_php/clear.md
#    - Response_php/clearCommands.md
    - Response_php/confirmCommands.md
#    - Response_php/contextAppend.md
#    - Response_php/contextAssign.md
#    - Response_php/contextClear.md
#    - Response_php/contextPrepend.md
    - Response_php/create.md
    - Response_php/createInput.md
#    - Response_php/debug.md
#    - Response_php/domAppendChild.md
#    - Response_php/domAppendText.md
#    - Response_php/domCreateElement.md
#    - Response_php/domEndResponse.md
#    - Response_php/domInsertAfter.md
#    - Response_php/domInsertBefore.md
#    - Response_php/domRemoveChildren.md
#    - Response_php/domSetAttribute.md
#    - Response_php/domStartResponse.md
#    - Response_php/getCharacterEncoding.md
#    - Response_php/getCommandCount.md
#    - Response_php/getContentType.md
#    - Response_php/getOutput.md
    - Response_php/includeCSS.md
    - Response_php/includeScript.md
    - Response_php/includeScriptOnce.md
    - Response_php/insert.md
    - Response_php/insertAfter.md
    - Response_php/insertInput.md
    - Response_php/insertInputAfter.md
    - Response_php/plugin.md
    - Response_php/prepend.md
#   - Response_php/printOutput.md
    - Response_php/redirect.md
    - Response_php/remove.md
    - Response_php/removeCSS.md
    - Response_php/removeHandler.md
    - Response_php/removeScript.md
    - Response_php/replace.md
    - Response_php/script.md
#    - Response_php/sendHeaders.md
    - Response_php/setEvent.md
    - Response_php/setFunction.md
    - Response_php/setReturnValue.md
    - Response_php/sleep.md
    - Response_php/waitFor.md
    - Response_php/waitForCSS.md
#    - Response_php/wrapFunction.md
  - Xajax Class:
    - Xajax_php/addClassDir.md
    - Xajax_php/canProcessRequest.md
    - Xajax_php/challenge.md
    - Xajax_php/configure.md
    - Xajax_php/configureMany.md
    - Xajax_php/disableAutoLoad.md
    - Xajax_php/errorHandler.md
    - Xajax_php/exportJavascript.md
    - Xajax_php/getConfiguration.md
    - Xajax_php/getCss.md
    - Xajax_php/getJs.md
    - Xajax_php/getScript.md
    - Xajax_php/plugin.md
    - Xajax_php/printScript.md
    - Xajax_php/processRequest.md
    - Xajax_php/register.md
    - Xajax_php/registerClass.md
    - Xajax_php/registerClasses.md
    - Xajax_php/setJavascriptURI.md
    - Xajax_php/useComposerAutoLoader.md
- Xajax Javascript Classes:
  - Xajax.Core.js:
    - xajax.core_js/xajax.callback.global.md
    - xajax.core_js/xajax.callback.md
    - xajax.core_js/xajax.command.handler.md
    - xajax.core_js/xajax.command.md
    - xajax.core_js/xajax.config.cursor.md
    - xajax.core_js/xajax.config.md
    - xajax.core_js/xajax.config.status.md
    - xajax.core_js/xajax.css.md
    - xajax.core_js/xajax.dom.md
    - xajax.core_js/xajax.domResponse.md
    - xajax.core_js/xajax.events.md
    - xajax.core_js/xajax.forms.md
    - xajax.core_js/xajax.js.md
    - xajax.core_js/xajax.responseProcessor.md
    - xajax.core_js/xajax.tools.md
    - xajax.core_js/xajax.tools.queue.md
    - xajax.core_js/xajax.tools.xml.md
  